export type AiProvider = "openai" | "anthropic" | "gemini";

export type AiCredentialMode = "session" | "encrypted-local";

export type AiCredentialPolicy = {
  readonly provider: AiProvider;
  readonly mode: AiCredentialMode;
  readonly encrypted: boolean;
};

export type AiSuggestionKind =
  | "improve-writing"
  | "fix-grammar"
  | "rewrite"
  | "summarize"
  | "tags"
  | "categories"
  | "internal-links"
  | "social-post";

export type AiSuggestionRequest = {
  readonly kind: AiSuggestionKind;
  readonly selectedText: string;
  readonly contextMarkdown: string;
};

export type AiSuggestion = {
  readonly kind: AiSuggestionKind;
  readonly content: string;
  readonly requiresApproval: true;
};

export function createCredentialPolicy(
  provider: AiProvider,
  mode: AiCredentialMode = "session"
): AiCredentialPolicy {
  return {
    provider,
    mode,
    encrypted: mode === "encrypted-local"
  };
}

export function createSuggestion(request: AiSuggestionRequest, content: string): AiSuggestion {
  return {
    kind: request.kind,
    content,
    requiresApproval: true
  };
}

function buildGeminiPrompt(request: AiSuggestionRequest): string {
  const contextText = request.contextMarkdown ? `Context of the document:\n---\n${request.contextMarkdown}\n---\n` : "";
  const selectedText = request.selectedText ? `Selected text to analyze/modify:\n---\n${request.selectedText}\n---\n` : "";

  switch (request.kind) {
    case "improve-writing":
      return `${contextText}${selectedText}Improve the writing style of the selected text above. Keep the tone consistent with the document. Return ONLY the improved text. Do not add any explanation, commentary, markdown code blocks, or preamble.`;
    case "fix-grammar":
      return `${selectedText}Correct any grammar, spelling, punctuation, or formatting errors in the text above. Return ONLY the corrected text. Do not add any explanation, commentary, or preamble.`;
    case "rewrite":
      return `${contextText}${selectedText}Rewrite the selected text to be more clear, concise, and engaging. Return ONLY the rewritten text. Do not add any explanation, commentary, or preamble.`;
    case "summarize":
      return `${contextText}Summarize the document above. Return ONLY the summary. Do not add any explanation, commentary, or preamble.`;
    case "tags":
      return `${contextText}Suggest up to 5 relevant tags for the document above. Return ONLY a comma-separated list of tags (e.g. tag1, tag2, tag3). Do not add any explanation, commentary, or preamble.`;
    case "categories":
      return `${contextText}Suggest up to 3 relevant categories for the document above. Return ONLY a comma-separated list of categories (e.g. Category1, Category2). Do not add any explanation, commentary, or preamble.`;
    case "social-post":
      return `${contextText}Write an engaging social media post (e.g. for X/Twitter) to promote the document above. Keep it under 280 characters and include relevant tags. Return ONLY the post text.`;
    case "internal-links":
      return `${contextText}Analyze the document above and suggest 3 internal linking opportunities or anchor links that would improve the navigation. Return ONLY the suggestions as a bulleted list.`;
    default:
      return `${contextText}${selectedText}Analyze the text and assist the writer.`;
  }
}

export async function generateGeminiSuggestion(
  request: AiSuggestionRequest,
  apiKey: string
): Promise<AiSuggestion> {
  if (!apiKey) {
    throw new Error("Gemini API key is required");
  }

  const prompt = buildGeminiPrompt(request);
  const model = "gemini-2.5-flash";
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [
            {
              text: prompt
            }
          ]
        }
      ]
    })
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    const message = (errorData as any)?.error?.message || `Gemini API returned status ${response.status}`;
    throw new Error(message);
  }

  const data = (await response.json()) as any;
  const content = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!content) {
    throw new Error("No response content generated by Gemini API");
  }

  return {
    kind: request.kind,
    content: content.trim(),
    requiresApproval: true
  };
}
